Repository SUI-Components/sui-components, pull requests merged in 2020-10, with the labels that each got.

#1258 feat(Root): add Switch demos
  demo/atom/switch/playground
Labels: hacktoberfest, hacktoberfest-accepted

#1262 TextArea && TextAreaField demos
  components/molecule/textareaField/src/index.js
  demo/atom/textarea/playground
  demo/molecule/textareaField/demo/index.js
Labels: hacktoberfest-accepted

#1260 feat(molecule/breadcrumb): adds description and organize demos
  components/molecule/breadcrumb/README.md
  demo/molecule/breadcrumb/playground
Labels: hacktoberfest-accepted

#1257 feat(molecule/badgeCounter): add Large size and a custom prop to MoleculeBadgeConter
  components/molecule/badgeCounter/src/index.js
  components/molecule/badgeCounter/src/index.scss
  demo/molecule/badgeCounter/playground
Labels: WiP, not ready to merge

#1259 fix(Root): organize demo
  demo/atom/label/playground
Labels: hacktoberfest-accepted

#1278 TextArea - 100% width by default, for all Verticals
  components/atom/textarea/src/index.scss
  demo/atom/validationText/playground
Labels: hacktoberfest-accepted

#1277 feat(Root): organize validationText demos
  demo/atom/validationText/playground
Labels: hacktoberfest-accepted

#1276 feat(Root): organize rating demos
  demo/molecule/rating/demo/index.js
  demo/molecule/rating/demo/index.scss
  demo/molecule/rating/playground
Labels: hacktoberfest-accepted
