Repository SUI-Components/sui-components, pull requests merged in 2021-11, with the labels that each got.

#1863 fix(components/atom/tag): fix typo in isFitted prop type
  components/atom/tag/src/index.js
Labels: hacktoberfest-accepted

#1862 fix(components/atom/badge): fix typo in isFitted prop type
  components/atom/badge/src/AtomBadge.js
Labels: hacktoberfest-accepted

#1864 fix(components/atom/card): Add card demo improvements
  components/atom/card/demo/index.js
  components/atom/card/src/index.js
Labels: hacktoberfest-accepted

#1867 fix(components/molecule/autosuggest): Width of the dropdown is differ…
  components/molecule/autosuggest/src/index.scss
Labels: hacktoberfest-accepted, ★★☆☆☆☆ Medium

#1871 chore(Root): wip
  .github/SCRIPTS/commentCoverage.js
  .github/SCRIPTS/exportCoverageFromJsonSummary.js
  .github/SCRIPTS/exportCoverageFromMarkdownShields.js
  .github/SCRIPTS/updateCoverageBadges.js
  .github/workflows/node.js.yml
  package.json
  scripts/replace-coverage-badges.js
Labels: WiP
