Repository SUI-Components/sui-components, pull requests merged in 2022-10, with the labels that each got.

#2351 ✨AtomImage Injector replacement of cloneElement to the spinner #2320
  components/atom/image/package.json
  components/atom/image/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2350 docs(components/atom/skeleton/demo): Update skeleton demo
  components/atom/skeleton/demo/ArticleVariant.js
Labels: hacktoberfest-accepted, hacktoberfest

#2355 docs(components/atom/slider): Add AtomSlider marker prop doc
  components/atom/slider/README.md
  components/atom/slider/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2359 chore(Root): add issue test template
  .github/ISSUE_TEMPLATE/test.yml
Labels: hacktoberfest-accepted, hacktoberfest

#2345 Refactor/2330 avatar fallback injector
  components/molecule/avatar/package.json
  components/molecule/avatar/src/AvatarFallback/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2343 refactor(components/molecule/field): replace cloneElement with injector
  components/molecule/field/package.json
  components/molecule/field/src/Label.js
Labels: hacktoberfest-accepted, hacktoberfest

#2362 fix(components/atom/image): update proptype
  components/atom/image/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2323 docs(Root): improve the commit message documentation
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest

#2366 ✨field refactor #2334
  components/molecule/field/src/Label.js
Labels: hacktoberfest-accepted, hacktoberfest

#2388 docs(Root): put correct links on the homepage of SUI Components
  components/README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#2389 feat(components/atom/popover): add icon color type
  components/atom/popover/demo/ArticleType.js
  components/atom/popover/demo/index.scss
  components/atom/popover/src/styles/index.scss
Labels: hacktoberfest-accepted, hacktoberfest

#2390 fix(component/molecule/accordion): The arrows are upside down
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#2393 fix(component/molecule/accordion): icon transition
  components/molecule/accordion/src/styles/index.scss
Labels: hacktoberfest-accepted, hacktoberfest

#2394 fix(components/molecule/select): accept onblur prop
  components/molecule/select/src/index.js
  components/molecule/select/test/index.test.js
Labels: hacktoberfest-accepted, hacktoberfest

#2279 feat(components/molecule/tabs): make tabs accesibles
  components/molecule/tabs/src/components/MoleculeTab.js
  components/molecule/tabs/src/components/MoleculeTabs.js
  components/molecule/tabs/test/index.test.js
Labels: hacktoberfest-accepted, hacktoberfest

#2400 fix(components/atom/checkbox): return handler name properly
  components/atom/checkbox/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2385 docs(Root): Remove the section UX Specs from all demos
  components/atom/actionButton/UXDEF.md
  components/atom/backToTop/UXDEF.md
  components/atom/badge/UXDEF.md
  components/atom/button/UXDEF.md
  components/atom/card/UXDEF.md
  components/atom/checkbox/UXDEF.md
  components/atom/helpText/UXDEF.md
  components/atom/icon/UXDEF.md
  components/atom/image/UXDEF.md
  components/atom/input/UXDEF.md
  components/atom/label/UXDEF.md
  components/atom/panel/UXDEF.md
  components/atom/progressBar/UXDEF.md
  components/atom/radioButton/UXDEF.md
  components/atom/slider/UXDEF.md
  components/atom/spinner/UXDEF.md
  components/atom/switch/UXDEF.md
  components/atom/tag/UXDEF.md
  components/atom/tooltip/UXDEF.md
  components/atom/upload/UXDEF.md
  components/behavior/sticky/UXDEF.md
  components/molecule/accordion/UXDEF.md
  components/molecule/autosuggest/UXDEF.md
  components/molecule/autosuggestField/UXDEF.md
  components/molecule/badgeCounter/UXDEF.md
  components/molecule/breadcrumb/UXDEF.md
  components/molecule/buttonGroup/UXDEF.md
  components/molecule/checkboxField/UXDEF.md
  components/molecule/collapsible/UXDEF.md
  components/molecule/dataCounter/UXDEF.md
  components/molecule/dropdownList/UXDEF.md
  components/molecule/dropdownOption/UXDEF.md
  components/molecule/inputField/UXDEF.md
  components/molecule/modal/UXDEF.md
  components/molecule/notification/UXDEF.md
  components/molecule/pagination/UXDEF.md
  components/molecule/progressSteps/UXDEF.md
  components/molecule/quickAction/UXDEF.md
  components/molecule/radioButtonField/UXDEF.md
  components/molecule/radioButtonGroup/UXDEF.md
  components/molecule/rating/UXDEF.md
  components/molecule/select/UXDEF.md
  components/molecule/selectField/UXDEF.md
  components/molecule/tabs/UXDEF.md
  components/molecule/textareaField/UXDEF.md
  components/molecule/thumbnail/UXDEF.md
Labels: hacktoberfest-accepted, hacktoberfest

#2395 Feature/nodelabel checkbox click
  README.md
  components/atom/checkbox/src/index.js
  components/atom/label/src/index.js
  components/atom/popover/demo/articles/ArticleArrow.js
  components/atom/popover/demo/articles/ArticleBehavior.js
  components/atom/popover/demo/articles/ArticleCloseIcon.js
  components/atom/popover/demo/articles/ArticleDefault.js
  components/atom/popover/demo/articles/ArticlePosition.js
  components/atom/popover/demo/articles/ArticleRef.js
  components/atom/popover/demo/articles/ArticleType.js
  components/atom/popover/demo/index.js
  components/molecule/checkboxField/demo/ArticleWithCustomCheckedIcon.js
  components/molecule/checkboxField/demo/index.js
  components/molecule/field/src/Label.js
  components/molecule/field/src/config.js
  components/molecule/field/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2405 refactor(components/molecule/imageEditor): useEffect has a missing dependency
  components/molecule/imageEditor/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2406 refactor(components/atom/popover): lint
  components/atom/popover/demo/Content.js
  components/atom/popover/demo/articles/ArticleArrow.js
  components/atom/popover/demo/articles/ArticleCloseIcon.js
  components/atom/popover/demo/index.js
  components/atom/popover/demo/settings.js
  components/atom/popover/src/PopoverExtendChildren.js
  components/atom/popover/src/config.js
Labels: hacktoberfest-accepted, hacktoberfest

#2407 fix(components/atom/popover): condition error
  components/atom/popover/src/config.js
  components/atom/tooltip/src/TooltipExtendChildren.js
  components/atom/tooltip/src/config.js
Labels: hacktoberfest-accepted, hacktoberfest

#2409 fix(components/hook/usePortal): portal targetting invalid element when isOpened on mounting
  components/hook/usePortal/demo/articles/ArticleCloseOnEvent.js
  components/hook/usePortal/demo/articles/ArticleCustom.js
  components/hook/usePortal/demo/articles/ArticleDefault.js
  components/hook/usePortal/demo/articles/ArticleStateful.js
  components/hook/usePortal/demo/articles/ArticleStateless.js
  components/hook/usePortal/demo/articles/ArticleTarget.js
  components/hook/usePortal/src/index.js
  components/hook/usePortal/test/index.test.js
Labels: hacktoberfest-accepted, hacktoberfest

#2411 DOCS: update component docs
  components/atom/actionButton/README.md
  components/atom/actionButton/assets/action-button-colors.png
  components/atom/actionButton/assets/action-button-sizes-states.png
  components/atom/badge/README.md
  components/atom/button/README.md
  components/atom/button/assets/screenshot.png
  components/atom/helpText/.npmignore
  components/atom/helpText/README.md
  components/atom/label/.npmignore
  components/atom/label/README.md
  components/atom/skeleton/.npmignore
  components/atom/skeleton/README.md
  components/atom/spinner/.npmignore
  components/atom/spinner/README.md
  components/atom/table/.npmignore
  components/atom/table/README.md
  components/atom/table/assets/preview.png
  components/atom/validationText/.npmignore
  components/atom/validationText/README.md
  components/molecule/collapsible/.npmignore
  components/molecule/collapsible/README.md
  components/molecule/drawer/README.md
  components/molecule/drawer/assets/drawer-preview.png
  components/molecule/thumbnail/.npmignore
  components/molecule/thumbnail/README.md
  components/molecule/validationCode/.npmignore
  components/molecule/validationCode/README.md
  components/primitive/injector/.npmignore
  components/primitive/injector/README.md
Labels: enhancement, documentation, hacktoberfest-accepted, hacktoberfest

#2413 chore(Root): confirm flag is deprecated, use --yes flag instead
  .github/workflows/node.js.yml
Labels: hacktoberfest-accepted, hacktoberfest

#2412 refactor(components/molecule/selectPopover): Add missing dependency o…
  components/molecule/selectPopover/src/index.js
  components/molecule/selectPopover/test/index.test.js
Labels: hacktoberfest

#2418 refactor(components/molecule/radioButtonGroup): replace cloneElement for injector
  components/molecule/radioButtonGroup/demo/articles/ArticleAtomRadioButton.js
  components/molecule/radioButtonGroup/demo/articles/ArticleChangeProps.js
  components/molecule/radioButtonGroup/demo/articles/ArticleMoleculeRadioButtonField.js
  components/molecule/radioButtonGroup/demo/articles/ArticleWithIcons.js
  components/molecule/radioButtonGroup/demo/index.js
  components/molecule/radioButtonGroup/package.json
  components/molecule/radioButtonGroup/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2398 feat(components/molecule/selectPopover): show overlay from selected type
  components/molecule/selectPopover/demo/index.js
  components/molecule/selectPopover/demo/index.scss
  components/molecule/selectPopover/demo/package.json
  components/molecule/selectPopover/package.json
  components/molecule/selectPopover/src/config.js
  components/molecule/selectPopover/src/index.js
  components/molecule/selectPopover/src/styles/index.scss
  components/molecule/selectPopover/src/styles/settings.scss
  components/molecule/selectPopover/test/index.test.js
Labels: hacktoberfest-accepted, hacktoberfest

#2422 fix(components/hook/usePortal): usePortal become SSR friendly
  components/hook/usePortal/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2423 docs(components/molecule/avatar): update fallbackColor docs
  components/molecule/avatar/demo/ArticleImage.js
Labels: hacktoberfest-accepted, hacktoberfest

#2424 2380 demo panel all thumbnails should be 100px squares
  components/atom/panel/demo/PanelAsImage/ArticleHorizontallyCropped.js
  components/atom/panel/demo/PanelAsImage/ArticleOverlay.js
  components/atom/panel/demo/PanelAsImage/ArticlePlaceholder.js
  components/atom/panel/demo/PanelAsImage/ArticleVerticallyCropped.js
Labels: enhancement, documentation, hacktoberfest-accepted

#2425 docs(components/molecule/radioButtonGroup/demo): add custom label tooltiped to the demo
  components/molecule/radioButtonGroup/demo/articles/ArticleMoleculeRadioButtonField.js
  components/molecule/radioButtonGroup/demo/components/CustomLabel.js
  components/molecule/radioButtonGroup/demo/package.json
Labels: hacktoberfest-accepted, hacktoberfest

#2428 refactor(components/hook/usePortal/demo): remove unnecessary dependency
  components/hook/usePortal/demo/articles/ArticleCustom/useTooltip.js
Labels: hacktoberfest-accepted, hacktoberfest

#2430 feat(components/molecule/selectPopover): improve overlay behavior
  components/molecule/selectPopover/src/index.js
  components/molecule/selectPopover/src/styles/index.scss
  components/molecule/selectPopover/src/styles/settings.scss
Labels: hacktoberfest-accepted, hacktoberfest

#2442 test(components/hook/usePortal): add tests to usePortal
  components/hook/usePortal/test/index.test.js
Labels: hacktoberfest-accepted, hacktoberfest

#2441 Feat/atom slider fullwidth
  components/atom/slider/demo/ArticleSliderFullWidth.js
  components/atom/slider/demo/index.js
  components/atom/slider/src/index.js
  components/atom/slider/src/markerFactory.js
  components/atom/slider/src/settings.js
  components/atom/slider/src/styles/index.scss
  components/atom/slider/src/styles/settings.scss
Labels: hacktoberfest-accepted, hacktoberfest

#2446 fix(components/molecule/radioButtonGroup): props not being passed
  components/molecule/radioButtonGroup/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest

#2451 Delete CLS on Drawer movement
  components/molecule/drawer/src/styles/index.scss
Labels: hacktoberfest-accepted, hacktoberfest
